export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const GET_PRODUCT_DETAILS_REQUEST = "GET_PRODUCT_DETAILS_REQUEST";
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS";
export const GET_PRODUCT_DETAILS_ERROR = "GET_PRODUCT_DETAILS_ERROR";

export const GET_ADS_REQUEST = "GET_ADS_REQUEST";
export const GET_ADS_SUCCESS = "GET_ADS_SUCCESS";
export const GET_ADS_ERROR = "GET_ADS_ERROR";

export const CREATE_BOOKING_REQUEST = "CREATE_BOOKING_REQUEST";
export const CREATE_BOOKING_SUCCESS = "CREATE_BOOKING_SUCCESS";
export const CREATE_BOOKING_ERROR = "CREATE_BOOKING_ERROR";

export const GET_BOOKING_DETAILS_REQUEST = "GET_BOOKING_DETAILS_REQUEST";
export const GET_BOOKING_DETAILS_SUCCESS = "GET_BOOKING_DETAILS_SUCCESS";
export const GET_BOOKING_DETAILS_ERROR = "GET_BOOKING_DETAILS_ERROR";

export const GET_BOOKING_LIST_REQUEST = "GET_BOOKING_LIST_REQUEST";
export const GET_BOOKING_LIST_SUCCESS = "GET_BOOKING_LIST_SUCCESS";
export const GET_BOOKING_LIST_ERROR = "GET_BOOKING_LIST_ERROR";

export const GET_PRODUCTS_RESET = "GET_PRODUCTS_RESET";
export const GET_PRODUCT_DETAILS_RESET = "GET_PRODUCT_DETAILS_RESET";
export const LOGIN_RESET = "LOGIN_RESET";
export const REGISTER_RESET = "REGISTER_RESET";
export const GET_ADS_RESET = "GET_ADS_RESET";
export const CREATE_BOOKING_RESET = "CREATE_BOOKING_RESET";
export const GET_BOOKING_LIST_RESET = "GET_BOOKING_LIST_RESET";
export const GET_BOOKING_DETAILS_RESET = "GET_BOOKING_DETAILS_RESET";

export const ID_MONTH = ["Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember"];
